import Cursor from '../components/Cursor'
import Footer from '../components/Footer'
import Header from '../components/Header'
import './globals.css'
import Bgimage from '../../public/bg.png'
import Script from 'next/script'
import { NextAuthProvider } from './providers'

export const metadata = {
  title: 'Ceres Kitchen',
  description: 'Generated by Ceres Kitchen',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} style={{
        backgroundImage: `url(${Bgimage.src})`,
        backgroundSize: 'cover',
        backgroundAttachment: 'fixed',
        backgroundPosition: 'center'
      }}>
        <NextAuthProvider>
          <Header />
          {children}
          <Cursor />
          <Footer />
          <Script src='JS/main.js' />
        </NextAuthProvider>
      </body>
    </html>
  )
}
