import Cursor from '../components/Cursor'
import Footer from '../components/Footer'
import Header from '../components/Header'
import './globals.css'
import Script from 'next/script'
import { NextAuthProvider } from './providers'

export const metadata = {
  title: 'Ceres Kitchen',
  description: 'Generated by Ceres Kitchen',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <NextAuthProvider>
          <Header />
          {children}
          <Script src='JS/main.js' />
          <Cursor />
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  )
}
